// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

export const meta = {
  admin: {
    checkUserAdminStatus: { auth: 'required', role: 'admin', type: 'query' },
    getAllUsers: { auth: 'required', limit: 20, type: 'query' },
    getDashboardStats: { auth: 'required', role: 'admin', type: 'query' },
    grantAdminByEmail: { auth: 'required', role: 'admin', type: 'mutation' },
    updateUserRole: { auth: 'required', role: 'admin', type: 'mutation' },
  },
  organization: {
    acceptInvitation: { auth: 'required', type: 'mutation' },
    cancelInvitation: { auth: 'required', rateLimit: 'organization/cancelInvite', type: 'mutation' },
    createOrganization: { auth: 'required', rateLimit: 'organization/create', type: 'mutation' },
    deleteOrganization: { auth: 'required', type: 'mutation' },
    getOrganization: { auth: 'required', type: 'query' },
    getOrganizationOverview: { auth: 'required', type: 'query' },
    inviteMember: { auth: 'required', rateLimit: 'organization/invite', type: 'mutation' },
    leaveOrganization: { auth: 'required', rateLimit: 'organization/leave', type: 'mutation' },
    listMembers: { auth: 'required', type: 'query' },
    listOrganizations: { auth: 'required', type: 'query' },
    listPendingInvitations: { auth: 'required', type: 'query' },
    rejectInvitation: { auth: 'required', rateLimit: 'organization/rejectInvite', type: 'mutation' },
    removeMember: { auth: 'required', rateLimit: 'organization/removeMember', type: 'mutation' },
    setActiveOrganization: { auth: 'required', rateLimit: 'organization/setActive', type: 'mutation' },
    updateMemberRole: { auth: 'required', rateLimit: 'organization/updateRole', type: 'mutation' },
    updateOrganization: { auth: 'required', rateLimit: 'organization/update', type: 'mutation' },
  },
  projects: {
    addMember: { auth: 'required', rateLimit: 'project/member', type: 'mutation' },
    archive: { auth: 'required', rateLimit: 'project/update', type: 'mutation' },
    create: { auth: 'required', rateLimit: 'project/create', type: 'mutation' },
    get: { type: 'query' },
    leave: { auth: 'required', rateLimit: 'project/member', type: 'mutation' },
    list: { auth: 'optional', limit: 20, type: 'query' },
    listForDropdown: { auth: 'required', type: 'query' },
    removeMember: { auth: 'required', rateLimit: 'project/member', type: 'mutation' },
    restore: { auth: 'required', rateLimit: 'project/update', type: 'mutation' },
    transfer: { auth: 'required', rateLimit: 'project/update', type: 'mutation' },
    update: { auth: 'required', rateLimit: 'project/update', type: 'mutation' },
  },
  seed: {
    generateSamples: { auth: 'required', type: 'action' },
  },
  tags: {
    create: { auth: 'required', rateLimit: 'tag/create', type: 'mutation' },
    deleteTag: { auth: 'required', rateLimit: 'tag/delete', type: 'mutation' },
    list: { auth: 'required', type: 'query' },
    merge: { auth: 'required', rateLimit: 'tag/update', type: 'mutation' },
    popular: { auth: 'required', type: 'query' },
    update: { auth: 'required', rateLimit: 'tag/update', type: 'mutation' },
  },
  todoComments: {
    addComment: { auth: 'required', rateLimit: 'todoComment/create', type: 'mutation' },
    deleteComment: { auth: 'required', rateLimit: 'todoComment/update', type: 'mutation' },
    getCommentThread: { type: 'query' },
    getTodoComments: { auth: 'optional', limit: 20, type: 'query' },
    getUserComments: { auth: 'optional', limit: 20, type: 'query' },
    toggleReaction: { auth: 'required', rateLimit: 'todoComment/reaction', type: 'mutation' },
    updateComment: { auth: 'required', rateLimit: 'todoComment/update', type: 'mutation' },
  },
  todos: {
    bulkDelete: { auth: 'required', rateLimit: 'todo/delete', type: 'mutation' },
    create: { auth: 'required', rateLimit: 'todo/create', type: 'mutation' },
    deleteTodo: { auth: 'required', rateLimit: 'todo/delete', type: 'mutation' },
    get: { auth: 'required', type: 'query' },
    list: { auth: 'optional', limit: 20, type: 'query' },
    reorder: { auth: 'required', rateLimit: 'todo/update', type: 'mutation' },
    restore: { auth: 'required', rateLimit: 'todo/update', type: 'mutation' },
    search: { auth: 'optional', limit: 20, type: 'query' },
    toggleComplete: { auth: 'required', rateLimit: 'todo/update', type: 'mutation' },
    update: { auth: 'required', rateLimit: 'todo/update', type: 'mutation' },
  },
  user: {
    getCurrentUser: { auth: 'required', type: 'query' },
    getIsAuthenticated: { type: 'query' },
    getSessionUser: { auth: 'optional', type: 'query' },
    updateSettings: { auth: 'required', type: 'mutation' },
  },
} as const;

export type Meta = typeof meta;
